var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "domingo",
            "mon": "lunes",
            "tue": "martes",
            "wed": "miercoles",
            "thu": "jueves",
            "fri": "viernes",
            "sat": "sabado",
            "jan": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "No implementado todavia",
        "to_date_view": "Click para ver la fecha actual",
        "i_undefined": "No definido",
        "allday_event": "Todo el Día",
        "repeat_event": "Repetir evento",
        "time": "Fecha",
        "event": "Evento",
        "location": "Ubicacion",
        "participant": "Participante",
        "get_data_exception": "Excepcion al obtener datos",
        "new_event": "Nuevo evento",
        "confirm_delete_event": "Confirme que desea borrar este evento? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Error en formato de datos! ",
        "invalid_title": "El titulo del evento no puede ser vacio o no puede contener ($<>)",
        "view_no_ready": "La vista no esta lista",
        "example": "",
        "content": "",
        "create_event": "Crear evento",
        "update_detail": "Agendar",
        "click_to_detail": "Ver detalles",
        "i_delete": "Eliminar",
        "day_plural": "days",
        "others": "Otras ",
        "item": ""
    }
});
