var i18n = $.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "domingo",
            "mon": "lunes",
            "tue": "martes",
            "wed": "miercoles",
            "thu": "jueves",
            "fri": "viernes",
            "sat": "sabado",
            "jan": "Ene",
            "feb": "Feb",
            "mar": "Mar",
            "apr": "Abr",
            "may": "May",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dic"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "Todo el Día",
        "repeat_event": "Repeat event",
        "time": "Fecha",
        "event": "Event",
        "location": "Location",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "New event",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "",
        "content": "",
        "create_event": "Create event",
        "update_detail": "Agendar",
        "click_to_detail": "View details",
        "i_delete": "Eliminar",
        "day_plural": "days",
        "others": "Others",
        "item": ""
    }
});
